### ISSUE TITLE
要件定義とか考えなきゃ！

### ISSUE THREAD

**Issue by potyama** [potyama/software_design#12]
大変大変！
要件定義とか考えないといけないじゃない！
何やるかちゃんと覚えてないけど、それもゆっくり考えていきましょう！

とりあえず、Readme.mdに追加する形で

**Comment by potyama** [comment]
紙に @son1moon が書いてくれてる

**Comment by potyama** [comment]
一応、過去の産物からとってきたやつだけど、

```
1. 概要

2. 要求仕様
　2.1. ゲームシステム
　2.2. ゲーム内要素
　2.3. インターフェース
　2.4. 外部データ読み込み(正直これはいらないと思う)

3. テスト計画
　3.1. 単体テスト
　3.2. 結合テスト
　3.3. 全体テスト

4. 設計書
　4.1. データ構造
　4.2. 関数仕様

5. テスト
　5.1. 単体テスト
　5.2. 結合テスト
　5.3. 全体テスト
```

と目次を見るとなっていました。
とりあえず、明日の朝に(覚えていたら)これらのissueを立てるので、12月くらいまでにはテスト系を終わらせたいと思ってます。

**Comment by onokatio** [comment]
要件と設計は別で、今回は要件定義では以下の内容さえ定義すればいいと思う

- 機能要件: どんな機能があって何を解決できるか
- 画面要件: アプリケーションの画面はどう見えるか


要件定義は「何を満たせば完成と言えるか」とを定義して、詳細設計は「要件をどう実現するか」の話
