### ISSUE TITLE
英語の問題をどういうタイミングで出すか

### ISSUE THREAD

**Issue by potyama** [potyama/software_design#14]
今のままだと、どのタイミングで出すのかわからないので、意見を聞きたいです。
@onokatio 
@son1moon 
@WalkerZC 

一応、 @WalkerZC は
「再試みたいな感じで40~50のときに出すでいいんじゃない?」
とのことでしたが、更に意見あったらどんどん書き込んでね。

**Comment by onokatio** [comment]
基本ランダムに出すのは？

**Comment by potyama** [comment]
どうしても、偏ってしまう(=できれば均等に出したい)からどう出そうかなと思ってたけど、
ランダムでもいいか？

**Comment by onokatio** [comment]
いいと思う

**Comment by potyama** [comment]
#17
