### ISSUE TITLE
英訳について

### ISSUE THREAD

**Issue by potyama** [potyama/software_design#5]
今ある英語だと文法的におかしいと思うので、 @WalkerZC に英訳をしてもらう

**Comment by potyama** [comment]
1.
あなたの学年は%d年です。
留年回数は%d回で、今は%dターン目です。

2.
あなたの点数は%dです。赤点から%d点はなれています。。

3.
おめでとう！学年が上がったよ！次も頑張ろう！

4.
あらら.... 留年しちゃった。
どんまい！
次切り替えていこう！

**Comment by WalkerZC** [comment]
1. 
You're currently a %d year student.
You repeated your grade %d time(s). This is your %d time(s).

2.
Your marks is %d. You are %d away from failing..

3.
Congrats! You went up a grade! Let's keep at it for the next one too!

4.
Oh my... Looks like you gonna have to repeat the year.
Don't worry!
Let's get better for the next one!

これでいいと思うよ！

**Comment by potyama** [comment]
thx!!!!!

修正しておきます！
