### ISSUE TITLE
英語問題の追加検討

### ISSUE THREAD

**Issue by potyama** [potyama/software_design#8]
現在考えている出し方
- 英単語をソートしてもとの単語がなにか当てる。
  - apple -> aelpp とかにして。

- 選択問題
 - app()eのかっこにはいるアルファベットはなにか (1, l 2,k 3,j 4,e)

**Comment by potyama** [comment]
英単語は簡単にゲットできそう。

**Comment by onokatio** [comment]
テキストデータならこういうのがある
https://ftp.gnu.org/gnu/aspell/dict/0index.html

**Comment by onokatio** [comment]
例えば英語辞書の内容はこれ
https://gist.github.com/onokatio/c1648769454f8370fb2fd749acd21386

**Comment by WalkerZC** [comment]
> app()eのかっこにはいるアルファベットはなにか (1, l 2,k 3,j 4,e)

空いているところに、文字を入力して、辞書にその言葉が入っているかどうかをチェックすること
あるならOKで、辞書になかったら×で

**Comment by potyama** [comment]
> > app()eのかっこにはいるアルファベットはなにか (1, l 2,k 3,j 4,e)
> 
> 
> 空いているところに、文字を入力して、辞書にその言葉が入っているかどうかをチェックすること
> 
> あるならOKで、辞書になかったら×で

これ、ソートのやつでも同じことできそう？
両方出せそう

**Comment by WalkerZC** [comment]
できると思う

**Comment by potyama** [comment]
#17
